### ISSUE TITLE
bad argument #4 to `shape_full` error.

### ISSUE THREAD

**Issue by u-fischer** [khaledhosny/luahbtex-harf#29]
Running a simple document like

~~~
\documentclass{article}

\usepackage{luatexbase}
\directlua{require("harf-luaotfload.lua")}

\begin{document}
\font\test={file:texgyreheros-regular.otf:mode=harf;}
\test abc
\end{document}
~~~

I get the error 
~~~
warning  (node filter): error: .../luaotfload/texmf/tex/luatex/luahbtex-harf/ha
rf-node.lua:339: bad argument #4 to 'shape_full' (number expected, got table)
~~~

setting `shapers` to 0 in harf-node.lua (instead of a table) works, but I have naturally no idea which number the function expects.

**Comment by khaledhosny** [comment]
I can’t reproduce this (I needed 0a1605571b7c937001672a3867c1826ccbdfa70d and 437f3e2e6477d69a97c46ddd4c45b80858b78975 to get the test working, though).

**Comment by khaledhosny** [comment]
You might need a recent luahbtex build as handling shapers is a later addition to luaharfbuzz.

**Comment by u-fischer** [comment]
Ah. With the newest luahbtex it worked (I hadn't seen that it isn't TLW64 folder but in the win64 folder).
