### ISSUE TITLE
With fontspec luaotfload seems to still load the fonts itself

### ISSUE THREAD

**Issue by khaledhosny** [khaledhosny/luahbtex-harf#30]
Not sure if this is new, but today the LaTeX example took so long and froze my system while consuming all available memory, which usually happens when luaotfload loads Noto Serif CJK, but it shouldn’t be loading any fonts. Might be related to the fact that with fontspec both `mode=node` and `mode=harf` are used.

**Comment by khaledhosny** [comment]
There should be no more `mode=node` after d9f6ec1a269f27e214b1fc4fe4321d0255a960c4, but it still does not fix the issue.

**Comment by khaledhosny** [comment]
@u-fischer, @zauguin:
It seems that `fonts.definers.read` is always called first even if `mode=harf`is set. Is this expected, and if yes is there any way to override it and have my `fonts.readers.harf` called first and only call the other when it returns nil?

**Comment by u-fischer** [comment]
I can look tomorrow. How do you see that fonts.definers.read is called?

**Comment by khaledhosny** [comment]
I add a `print` after https://github.com/u-fischer/luaotfload/blob/401f60d473efb5953c38ad04680412ee2b14388e/src/luaotfload-loaders.lua#L135 and after https://github.com/khaledhosny/luahbtex-harf/blob/d9f6ec1a269f27e214b1fc4fe4321d0255a960c4/src/harf-luaotfload.lua#L14, and both are always called (the issue does not seem specif to LaTeX as I initially thought).

**Comment by zauguin** [comment]
@khaledhosny That's by design and can not be changed without rewriting bigger parts of `luaotfload` (or introducing an ugly hack):
`fonts.definers.read` is responsible for managing the whole lookup process, especially it is the function which (indirectly) is used to call `fonts.readers.harf`.
It should not actually load the font using the fontloader through if `mode=harf` is set, therefore the readers implementation might be buggy. The function doing the actual loading would be `fonts.readers.otf`.

**Comment by khaledhosny** [comment]
Thanks. So I tried with `opentypereader` in `fontloader-2018-12-19.lua`; with Plain it is never called, with LaTeX it is called several times before my loaders is called. Now I’m starting to suspect that it is somehow related to fontspec.

**Comment by khaledhosny** [comment]
The font specifications that get through to `opentypereader` seem to be without any options at all, I’m pretty sure these come from fontspec as it does its many font checks before loading the font for real.

I’m not sure what to do in this case.

**Comment by khaledhosny** [comment]
Looks like I can force a default luaotfload mode with a `luaotfload.conf` file:
```ini
[default-features]
  global = mode=harf
```

But this causes other interesting issues I need to handle (like how to override relevant `luaotfload.aux` functions to work on HarfBuzz-loaded fonts). Needs more investigation.

**Comment by u-fischer** [comment]
What is the problem with fonts.definers.read? Does is break something? I'm currently quite unsure if your problem is with luaotfload or fontspec. Can you make a small example? I can run some tests in the evening.

**Comment by khaledhosny** [comment]
It does not break anything, but it can be slow for very large fonts, which is waste of time if these fonts are not going to be handled with luaotfload’s node processor (for Noto Serif CJK font, loading it for the first time freezes the system consuming all available memory).

**Comment by u-fischer** [comment]
Hm, yes, I already had some cjk fonts freezing my system too. A few days ago I had to kill the compilation. I think we should look at this, but it will need a bit time - I'm busy in the next weeks.

**Comment by khaledhosny** [comment]
Fontspec issue.
