### ISSUE TITLE
Report missing characters

### ISSUE THREAD

**Issue by khaledhosny** [khaledhosny/luahbtex-harf#9]
For missing characters we currently output `.notdef` glyph (glyph 0 in the font), this is usually a box glyph or something similar which helps give visual indication that a character is not supported by the font (in contrast to traditional TeX behavior of outputting nothing).

This have the downside that messing character log messages are not shown, so we need to fix this.

**Comment by shreevatsa** [comment]
Just a +1 for this. I'll be happy if, further, missing characters are reported as errors; it would be better than the traditional TeX behaviour which trips up users (e.g. https://tex.stackexchange.com/questions/298583/why-are-missing-characters-reported-as-warnings-and-not-errors , https://tex.stackexchange.com/questions/41230/getting-xetex-to-complain-when-a-character-is-missing )

**Comment by khaledhosny** [comment]
I’m thinking of respecting the existing setting (`\tracingchars` I think) to not be too much distribution, bur if enough people thing this report to the terminal not only the log by default, I’m open to doing that.

**Comment by khaledhosny** [comment]
Making this an error is too disruptive though, and I’d not do that by default, but I’m open to having an option for it.
